# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Md. Arifin Ibne Matin
author: Md Arifin Ibne Matin
designation: Full Stack Web Application Developer
email: arifin4web@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A blog site maintained by Md. Arifin Ibne Matin. Though he is entitled as
  Full Stack Web Application Developer, He is basically a problem solver.
  Expert in building web apps and cooking Biryani.
blog_header: A collection of things I've learned in my day-to-day life deemed sharing.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://arifin4web.github.io" # the base hostname & protocol for your site
github_username:  arifin4web
disqus: arifin4web

# Build settings
markdown: kramdown
theme: minima
permalink: /blog/:title

gems:
  - jekyll-feed
